name: C++ ToDoList - CI

on:
  push:
    branches: [ main ]
    paths:
      - 'todo-list-cpp-doctest-make/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'todo-list-cpp-doctest-make/**'

# (évite d'empiler plusieurs runs sur la même branche)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    name: Ubuntu build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-list-cpp-doctest-make
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl lld

      - name: Build
        run: |
          make clean
          make

      - name: Run tests (doctest)
        run: ./bin/tests.exe --success=1

      - name: Upload artifacts (Ubuntu)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-artifacts
          path: |
            todo-list-cpp-doctest-make/bin/**
            todo-list-cpp-doctest-make/build/**

  windows-msys2:
    name: Windows (MSYS2 UCRT64) build & test
    runs-on: windows-latest
    defaults:
      run:
        working-directory: todo-list-cpp-doctest-make
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-wget
            mingw-w64-ucrt-x86_64-lld
            mingw-w64-ucrt-x86_64-curl

      - name: Build (mingw32-make)
        shell: msys2 {0}
        run: |
          mingw32-make clean
          # Si besoin d'utiliser LLD pour éviter l'erreur de lien 116, dé-commente la ligne suivante :
          # mingw32-make LDFLAGS+=' -fuse-ld=lld'
          mingw32-make

      - name: Run tests (doctest)
        shell: msys2 {0}
        run: ./bin/tests.exe --success=1

      - name: Upload artifacts (Windows)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            todo-list-cpp-doctest-make/bin/**
            todo-list-cpp-doctest-make/build/**
