# This workflow will build, tests, create tag and release a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: CI/CD - ToDoList (Ant+Ivy+JUnit)

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]               # si tu pousses un tag vX.Y.Z, on déploie aussi
  pull_request:
  workflow_dispatch:              # déclenchement manuel avec création du tag + release
    inputs:
      version:
        description: "Version (ex: v1.0.0)"
        required: true
        type: string
      notes:
        description: "Release notes (optionnel)"
        required: false
        type: string
        default: ""

permissions:
  contents: write                 # nécessaire pour créer/mettre à jour le tag et la release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: todo-list-ivy-java-ant

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant
          ant -version
          java -version

      - name: Cache Ivy dependencies (~/.ivy2/cache)
        uses: actions/cache@v4
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ hashFiles('todo-list-ivy-java-ant/ivy.xml') }}
          restore-keys: |
            ${{ runner.os }}-ivy-

      # Optionnel si tu conserves le jar d'Ivy dans tools/ivy
      - name: Cache local tools/ivy (optional)
        uses: actions/cache@v4
        with:
          path: todo-list-ivy-java-ant/tools/ivy
          key: ${{ runner.os }}-ivyjar-2.5.2
          restore-keys: |
            ${{ runner.os }}-ivyjar-

      - name: Resolve dependencies (Ivy)
        run: ant -Djdk.home="${JAVA_HOME}" resolve

      - name: Compile
        run: ant -Djdk.home="${JAVA_HOME}" compile

      - name: Compile tests
        run: ant -Djdk.home="${JAVA_HOME}" compile-tests

      - name: Run tests (JUnit 5)
        run: ant -Djdk.home="${JAVA_HOME}" test

      - name: Build JAR
        run: ant -Djdk.home="${JAVA_HOME}" jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: todo-list-jar
          path: todo-list-ivy-java-ant/dist/todo-list.jar
          if-no-files-found: error

      - name: Upload JUnit reports (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: todo-list-ivy-java-ant/build/reports/tests
          if-no-files-found: ignore

  tag-and-release:
    name: Create Tag & Release
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: todo-list-jar
          path: dist

      # Crée ou met à jour le tag seulement si lancé en workflow_dispatch
      - name: Create/Update tag (handles empty version)
        if: github.event_name == 'workflow_dispatch'
        id: tag
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const rx = /^v\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
            let version = (core.getInput('version') || '').trim();
      
            // Auto-calc si input vide
            if (!version) {
              const { data: tags } = await github.rest.repos.listTags({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100
              });
              const versions = tags
                .map(t => t.name)
                .filter(n => rx.test(n))
                .sort((a,b) => {
                  const [A,B,C] = a.match(/\d+/g).map(Number);
                  const [X,Y,Z] = b.match(/\d+/g).map(Number);
                  return A-X || B-Y || C-Z;
                });
              if (versions.length) {
                const last = versions[versions.length - 1];
                const m = /^v(\d+)\.(\d+)\.(\d+)/.exec(last);
                const major = +m[1], minor = +m[2], patch = +m[3];
                version = `v${major}.${minor}.${patch+1}`;
                core.info(`Auto-bump: ${last} -> ${version}`);
              } else {
                version = 'v0.1.0';
                core.info(`No v* tag found, using ${version}`);
              }
            } else if (!rx.test(version)) {
              core.setFailed(`Invalid version: ${version}. Expected vMAJOR.MINOR.PATCH (e.g. v1.2.3)`);
              return;
            }
      
            // Crée / met à jour le tag sur le commit courant
            const sha = context.sha;
            const ref = `refs/tags/${version}`;
            try {
              await github.rest.git.getRef({ owner: context.repo.owner, repo: context.repo.repo, ref: `tags/${version}` });
              core.info(`Tag ${version} exists -> updating to ${sha}`);
              await github.rest.git.updateRef({ owner: context.repo.owner, repo: context.repo.repo, ref: `tags/${version}`, sha, force: true });
            } catch {
              core.info(`Creating tag ${version} at ${sha}`);
              await github.rest.git.createRef({ owner: context.repo.owner, repo: context.repo.repo, ref, sha });
            }
      
            core.setOutput('version', version);

      # Crée la release :
      # - si workflow_dispatch : tag = inputs.version
      # - si push de tag v* : tag = github.ref_name
      - name: Create GitHub Release & Upload JAR
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          name: Release ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          body: ${{ github.event_name == 'workflow_dispatch' && inputs.notes || '' }}
          files: |
            dist/todo-list.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
