name: CI/CD .NET ToDoListApp

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - "ToDoListNetSDK/**"
    tags:
      - "v*"
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - "ToDoListNetSDK/**"
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (format: vMAJOR.MINOR.PATCH[-rcX])"
        required: false
      prerelease:
        description: "Marquer la release comme préversion ?"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  APP_CSPROJ: ToDoListNetSDK/src/ToDoApp/ToDoApp.csproj
  TEST_CSPROJ: ToDoListNetSDK/tests/ToDoApp.Tests/ToDoApp.Tests.csproj

jobs:
  ci:
    name: Build & Test (.NET)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.x"

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: |
            ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: |
          dotnet restore "${{ env.APP_CSPROJ }}"
          dotnet restore "${{ env.TEST_CSPROJ }}"

      - name: Build (Debug)
        run: |
          dotnet build "${{ env.APP_CSPROJ }}" -c Debug --no-restore
          dotnet build "${{ env.TEST_CSPROJ }}" -c Debug --no-restore

      - name: Test
        run: dotnet test "${{ env.TEST_CSPROJ }}" -c Debug --no-build --verbosity normal

  release:
    name: Create Tag + Release + Publish DLL/EXE
    runs-on: windows-latest
    needs: [ci]
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.x"

      - name: Compute VERSION
        id: version
        shell: pwsh
        run: |
          $v = "${{ github.event.inputs.version }}".Trim()
          if (-not $v) {
            if ("${{ github.ref }}".StartsWith("refs/tags/")) {
              $v = "${{ github.ref }}".Replace("refs/tags/","")
            }
          }
          if (-not $v) {
            Write-Error "Aucune version fournie et ce n’est pas un push de tag."
            exit 1
          }
          if ($v -notmatch '^v\d+\.\d+\.\d+(-[0-9A-Za-z\.-]+)?$') {
            Write-Error "Version invalide: $v. Format attendu: vMAJOR.MINOR.PATCH"
            exit 1
          }
          "VERSION=$v" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "VERSION=$v"

      - name: Create or update tag (manual dispatch only)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            const version = process.env.VERSION;
            const sha = context.sha;
            const tagRef = `refs/tags/${version}`;
            try {
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${version}`
              });
              core.info(`Tag ${version} existe déjà -> mise à jour vers ${sha}`);
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${version}`,
                sha,
                force: true
              });
            } catch (e) {
              core.info(`Création du tag ${version} -> ${sha}`);
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: tagRef,
                sha
              });
            }

      - name: Restore
        run: |
          dotnet restore "${{ env.APP_CSPROJ }}"
          dotnet restore "${{ env.TEST_CSPROJ }}"

      - name: Build & Test (Release)
        run: |
          dotnet build "${{ env.APP_CSPROJ }}" -c Release --no-restore
          dotnet build "${{ env.TEST_CSPROJ }}" -c Release --no-restore
          dotnet test  "${{ env.TEST_CSPROJ }}" -c Release --no-build --verbosity normal

      # 1) Publication framework-dependent -> DLL + apphost (EXE) dans le ZIP
      - name: Publish (framework-dependent DLL + apphost)
        shell: pwsh
        run: |
          $out = "publish/fwdep"
          dotnet publish "${{ env.APP_CSPROJ }}" -c Release `
            -p:UseAppHost=true `
            --no-build -o "$out"
          Compress-Archive -Path "$out/*" -DestinationPath "ToDoApp-fwdep-${{ env.VERSION }}.zip"

      # 2) Publication Windows self-contained single-file -> EXE
      - name: Publish (win-x64 self-contained EXE)
        shell: pwsh
        run: |
          $out = "publish/win-x64"
          dotnet publish "${{ env.APP_CSPROJ }}" -c Release -r win-x64 `
            -p:PublishSingleFile=true -p:SelfContained=true -p:IncludeNativeLibrariesForSelfExtract=true `
            --no-build -o "$out"
          Compress-Archive -Path "$out/*" -DestinationPath "ToDoApp-win-x64-${{ env.VERSION }}.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp-${{ env.VERSION }}
          path: |
            ToDoApp-fwdep-${{ env.VERSION }}.zip
            ToDoApp-win-x64-${{ env.VERSION }}.zip
          if-no-files-found: error
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: |
            Release ${{ env.VERSION }} — ToDoApp (.NET 6)
            Artefacts:
            - Framework-dependent (DLL + apphost EXE): ToDoApp-fwdep-${{ env.VERSION }}.zip
            - Windows self-contained single-file (EXE): ToDoApp-win-x64-${{ env.VERSION }}.zip
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            ToDoApp-fwdep-${{ env.VERSION }}.zip
            ToDoApp-win-x64-${{ env.VERSION }}.zip
