name: CI/CD .NET ToDoListApp

on:
  push:
    branches: [ "main", "master" ]
    paths: [ "ToDoListNetSDK/**" ]
    tags:   [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]
    paths: [ "ToDoListNetSDK/**" ]
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (format: vMAJOR.MINOR.PATCH[-rcX])"
        required: false
      prerelease:
        description: "Marquer la release comme préversion ?"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  APP_CSPROJ: ToDoListNetSDK/src/ToDoApp/ToDoApp.csproj
  TEST_CSPROJ: ToDoListNetSDK/tests/ToDoApp.Tests/ToDoApp.Tests.csproj

jobs:
  ci:
    name: Build & Test (.NET)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Pin explicite du SDK .NET 6 via un global.json local au workspace
      - name: Pin SDK 6.0 via global.json
        shell: pwsh
        run: |
          '@{
            "sdk" = @{
              "version"     = "6.0.418"
              "rollForward" = "latestFeature"
            }
          }' | ConvertTo-Json -Depth 3 | Out-File -FilePath global.json -Encoding utf8

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Dotnet info
        run: dotnet --info

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore (net6.0)
        shell: pwsh
        run: |
          # Évite que des variables env écrasent des propriétés MSBuild
          Remove-Item Env:Version,Env:VERSION,Env:TargetFramework,Env:TARGETFRAMEWORK -ErrorAction SilentlyContinue
          dotnet restore "${{ env.APP_CSPROJ }}"
          dotnet restore "${{ env.TEST_CSPROJ }}"

      - name: Build (Debug, net6.0)
        run: |
          dotnet build "${{ env.APP_CSPROJ }}"  -c Debug --no-restore -f net6.0
          dotnet build "${{ env.TEST_CSPROJ }}" -c Debug --no-restore -f net6.0

      - name: Test (net6.0)
        run: dotnet test "${{ env.TEST_CSPROJ }}" -c Debug --no-build -f net6.0 --verbosity normal

  release:
    name: Create Tag + Release + Publish DLL/EXE
    runs-on: windows-latest
    needs: [ci]
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pin SDK 6.0 via global.json
        shell: pwsh
        run: |
          '@{
            "sdk" = @{
              "version"     = "6.0.418"
              "rollForward" = "latestFeature"
            }
          }' | ConvertTo-Json -Depth 3 | Out-File -FilePath global.json -Encoding utf8

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Dotnet info
        run: dotnet --info

      - name: Compute TAG & APP_VERSION
        id: vars
        shell: pwsh
        run: |
          $tag = "${{ github.event.inputs.version }}".Trim()
          if (-not $tag) {
            if ("${{ github.ref }}".StartsWith("refs/tags/")) { $tag = "${{ github.ref }}".Replace("refs/tags/","") }
          }
          if (-not $tag) { Write-Error "Aucune version fournie et ce n’est pas un push de tag."; exit 1 }
          if ($tag -notmatch '^v\d+\.\d+\.\d+(-[0-9A-Za-z\.-]+)?$') {
            Write-Error "Version invalide: $tag. Format attendu: vMAJOR.MINOR.PATCH"
            exit 1
          }
          $app = $tag.TrimStart('v')  # ex: 1.0.5
          "TAG=$tag"         | Out-File -FilePath $env:GITHUB_ENV -Append
          "APP_VERSION=$app" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "TAG=$tag"
          Write-Host "APP_VERSION=$app"

      - name: Create or update tag (manual dispatch only)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.TAG;
            const sha = context.sha;
            const refTag = `refs/tags/${tag}`;
            try {
              await github.rest.git.getRef({ owner: context.repo.owner, repo: context.repo.repo, ref: `tags/${tag}` });
              core.info(`Tag ${tag} existe déjà -> mise à jour vers ${sha}`);
              await github.rest.git.updateRef({ owner: context.repo.owner, repo: context.repo.repo, ref: `tags/${tag}`, sha, force: true });
            } catch (e) {
              core.info(`Création du tag ${tag} -> ${sha}`);
              await github.rest.git.createRef({ owner: context.repo.owner, repo: context.repo.repo, ref: refTag, sha });
            }

      - name: Restore (net6.0 + win-x64)
        shell: pwsh
        run: |
          Remove-Item Env:Version,Env:VERSION,Env:TargetFramework,Env:TARGETFRAMEWORK -ErrorAction SilentlyContinue
          # Utilise des propriétés MSBuild au lieu de --framework (qui est routé vers MSBuild)
          dotnet restore "${{ env.APP_CSPROJ }}"  -p:TargetFramework=net6.0 -p:RuntimeIdentifier=win-x64
          dotnet restore "${{ env.TEST_CSPROJ }}" -p:TargetFramework=net6.0

      - name: Build & Test (Release, net6.0)
        run: |
          dotnet build "${{ env.APP_CSPROJ }}"  -c Release --no-restore -f net6.0
          dotnet build "${{ env.TEST_CSPROJ }}" -c Release --no-restore -f net6.0
          dotnet test  "${{ env.TEST_CSPROJ }}" -c Release --no-build    -f net6.0 --verbosity normal

      # 1) Publication framework-dependent -> DLL + apphost EXE
      - name: Publish (framework-dependent, net6.0)
        shell: pwsh
        run: |
          $out = "publish/fwdep"
          dotnet publish "${{ env.APP_CSPROJ }}" -c Release -f net6.0 `
            -p:UseAppHost=true `
            --no-build -o "$out"
          if (!(Test-Path $out)) { throw "Output not found: $out" }
          Compress-Archive -Path "$out/*" -DestinationPath "ToDoApp-fwdep-${{ env.TAG }}.zip"

      # 2) Publication Windows self-contained single-file -> EXE
      - name: Publish (win-x64 self-contained, net6.0)
        shell: pwsh
        run: |
          $out = "publish/win-x64"
          dotnet publish "${{ env.APP_CSPROJ }}" -c Release -f net6.0 -r win-x64 `
            -p:PublishSingleFile=true -p:SelfContained=true -p:IncludeNativeLibrariesForSelfExtract=true `
            --no-build -o "$out"
          if (!(Test-Path $out)) { throw "Output not found: $out" }
          Compress-Archive -Path "$out/*" -DestinationPath "ToDoApp-win-x64-${{ env.TAG }}.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp-${{ env.TAG }}
          path: |
            ToDoApp-fwdep-${{ env.TAG }}.zip
            ToDoApp-win-x64-${{ env.TAG }}.zip
          if-no-files-found: error
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          body: |
            Release ${{ env.TAG }} — ToDoApp (.NET 6)
            Artefacts:
            - Framework-dependent (DLL + apphost EXE): ToDoApp-fwdep-${{ env.TAG }}.zip
            - Windows self-contained single-file (EXE): ToDoApp-win-x64-${{ env.TAG }}.zip
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            ToDoApp-fwdep-${{ env.TAG }}.zip
            ToDoApp-win-x64-${{ env.TAG }}.zip
