name: CI/CD .NET ToDoListApp

on:
  push:
    branches: [ "main", "master" ]
    paths: [ "ToDoListNetSDK/**" ]
    tags:   [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]
    paths: [ "ToDoListNetSDK/**" ]
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (format: vMAJOR.MINOR.PATCH[-rcX])"
        required: false
      prerelease:
        description: "Marquer la release comme préversion ?"
        required: false
        type: boolean
        default: false

permissions:
  contents: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  DOTNET_MULTILEVEL_LOOKUP: "0"
  APP_CSPROJ: ToDoListNetSDK/src/ToDoApp/ToDoApp.csproj
  TEST_CSPROJ: ToDoListNetSDK/tests/ToDoApp.Tests/ToDoApp.Tests.csproj
  # ⚠️ Ne pas définir DOTNET_ROOT ici (laisse setup-dotnet gérer)

jobs:
  ci:
    name: Build & Test (.NET)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Utilise le SDK 9.x qui supporte net6/net8/net9
      - name: Setup .NET 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Dotnet info
        run: dotnet --info

      - name: Detect TargetFramework (TFM) from csproj
        id: tfm
        shell: pwsh
        run: |
          [xml]$xml = Get-Content $env:APP_CSPROJ
          $tfm = $xml.Project.PropertyGroup.TargetFramework
          if (-not $tfm) {
            $tfms = $xml.Project.PropertyGroup.TargetFrameworks
            if ($tfms) { $tfm = ($tfms -split ';' | Select-Object -First 1) }
          }
          if (-not $tfm) { $tfm = 'net6.0' }
          "TFM=$tfm" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Detected TFM = $tfm"

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore
        shell: pwsh
        run: |
          Remove-Item Env:Version,Env:VERSION,Env:TargetFramework,Env:TARGETFRAMEWORK,Env:DOTNET_ROOT -ErrorAction SilentlyContinue
          dotnet restore "${{ env.APP_CSPROJ }}" -p:TargetFramework=${{ env.TFM }}
          dotnet restore "${{ env.TEST_CSPROJ }}" -p:TargetFramework=${{ env.TFM }}

      - name: Build (Debug)
        run: |
          dotnet build "${{ env.APP_CSPROJ }}"  -c Debug --no-restore -f ${{ env.TFM }}
          dotnet build "${{ env.TEST_CSPROJ }}" -c Debug --no-restore -f ${{ env.TFM }}

      - name: Test
        run: dotnet test "${{ env.TEST_CSPROJ }}" -c Debug --no-build -f ${{ env.TFM }} --verbosity normal

  release:
    name: Create Tag + Release + Publish DLL/EXE
    runs-on: windows-latest
    needs: [ci]
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Dotnet info
        run: dotnet --info

      - name: Detect TargetFramework (TFM) from csproj
        id: tfm
        shell: pwsh
        run: |
          [xml]$xml = Get-Content $env:APP_CSPROJ
          $tfm = $xml.Project.PropertyGroup.TargetFramework
          if (-not $tfm) {
            $tfms = $xml.Project.PropertyGroup.TargetFrameworks
            if ($tfms) { $tfm = ($tfms -split ';' | Select-Object -First 1) }
          }
          if (-not $tfm) { $tfm = 'net6.0' }
          "TFM=$tfm" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Detected TFM = $tfm"

      - name: Compute TAG & APP_VERSION
        id: vars
        shell: pwsh
        run: |
          $tag = "${{ github.event.inputs.version }}".Trim()
          if (-not $tag) {
            if ("${{ github.ref }}".StartsWith("refs/tags/")) { $tag = "${{ github.ref }}".Replace("refs/tags/","") }
          }
          if (-not $tag) { Write-Error "Aucune version fournie et ce n’est pas un push de tag."; exit 1 }
          if ($tag -notmatch '^v\d+\.\d+\.\d+(-[0-9A-Za-z\.-]+)?$') {
            Write-Error "Version invalide: $tag. Format attendu: vMAJOR.MINOR.PATCH"
            exit 1
          }
          $app = $tag.TrimStart('v')  # ex: 1.0.5
          "TAG=$tag"         | Out-File -FilePath $env:GITHUB_ENV -Append
          "APP_VERSION=$app" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "TAG=$tag"
          Write-Host "APP_VERSION=$app"

      - name: Create or update tag (manual dispatch only)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.TAG;
            const sha = context.sha;
            const refTag = `refs/tags/${tag}`;
            try {
              await github.rest.git.getRef({ owner: context.repo.owner, repo: context.repo.repo, ref: `tags/${tag}` });
              core.info(`Tag ${tag} existe déjà -> mise à jour vers ${sha}`);
              await github.rest.git.updateRef({ owner: context.repo.owner, repo: context.repo.repo, ref: `tags/${tag}`, sha, force: true });
            } catch (e) {
              core.info(`Création du tag ${tag} -> ${sha}`);
              await github.rest.git.createRef({ owner: context.repo.owner, repo: context.repo.repo, ref: refTag, sha });
            }

      - name: Restore (with RID for publish)
        shell: pwsh
        run: |
          Remove-Item Env:Version,Env:VERSION,Env:TargetFramework,Env:TARGETFRAMEWORK,Env:DOTNET_ROOT -ErrorAction SilentlyContinue
          dotnet restore "${{ env.APP_CSPROJ }}"  -p:TargetFramework=${{ env.TFM }} -p:RuntimeIdentifier=win-x64
          dotnet restore "${{ env.TEST_CSPROJ }}" -p:TargetFramework=${{ env.TFM }}

      - name: Build & Test (Release)
        run: |
          dotnet build "${{ env.APP_CSPROJ }}"  -c Release --no-restore -f ${{ env.TFM }}
          dotnet build "${{ env.TEST_CSPROJ }}" -c Release --no-restore -f ${{ env.TFM }}
          dotnet test  "${{ env.TEST_CSPROJ }}" -c Release --no-build -f ${{ env.TFM }} --verbosity normal

      # 1) Publication framework-dependent -> DLL + apphost EXE (selon TFM détecté)
      - name: Publish (framework-dependent)
        shell: pwsh
        run: |
          $out = "publish/fwdep"
          dotnet publish "${{ env.APP_CSPROJ }}" -c Release -f ${{ env.TFM }} `
            -p:UseAppHost=true `
            --no-build -o "$out"
          if (!(Test-Path $out)) { throw "Output not found: $out" }
          Compress-Archive -Path "$out/*" -DestinationPath "ToDoApp-fwdep-${{ env.TAG }}.zip"

      # 2) Publication Windows self-contained single-file -> EXE
      - name: Publish (win-x64 self-contained)
        shell: pwsh
        run: |
          $out = "publish/win-x64"
          dotnet publish "${{ env.APP_CSPROJ }}" -c Release -f ${{ env.TFM }} -r win-x64 `
            -p:PublishSingleFile=true -p:SelfContained=true -p:IncludeNativeLibrariesForSelfExtract=true `
            --no-build -o "$out"
          if (!(Test-Path $out)) { throw "Output not found: $out" }
          Compress-Archive -Path "$out/*" -DestinationPath "ToDoApp-win-x64-${{ env.TAG }}.zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp-${{ env.TAG }}
          path: |
            ToDoApp-fwdep-${{ env.TAG }}.zip
            ToDoApp-win-x64-${{ env.TAG }}.zip
          if-no-files-found: error
          retention-days: 7

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          body: |
            Release ${{ env.TAG }} — ToDoApp (.NET)
            Artefacts:
            - Framework-dependent (DLL + apphost EXE): ToDoApp-fwdep-${{ env.TAG }}.zip
            - Windows self-contained single-file (EXE): ToDoApp-win-x64-${{ env.TAG }}.zip
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            ToDoApp-fwdep-${{ env.TAG }}.zip
            ToDoApp-win-x64-${{ env.TAG }}.zip
